apiVersion: v1
kind: ConfigMap
metadata:
  name: storefront-config
  namespace: default
data:
  APP_ENV: 'development'
  VENDURE_API_URL: http://vendure-service.default.svc.cluster.local:3001/shop-api
